default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dti_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: dti_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: dti_production
  username: dti
  password: <%= ENV["DTI_DATABASE_PASSWORD"] %>
