default: &default
  menubar: false
  resize: false
  branding: false
  toolbar: styleselect | bold italic underline | undo redo | aligncenter alignleft alignright | bullist numlist | table
  plugins: lists


alternate:
  <<: *default
  toolbar: styleselect | bold italic | undo redo | table
  plugins:
    - table